### ISSUE TITLE
RethinkDB Database Panel

### ISSUE THREAD

**Issue by gmittal** [ProjectCopilot/vitals#1]
If you fire up RethinkDB, it serves a web app at `127.0.0.1:8080` where you can look at the various stats and analytics for the database. Given that this functionality comes built-in to RethinkDB, there's no coding required. We just need a way of setting it up such that it runs on the `vitals` backend, and that it also requires authentication (so we can be sure that we're the only ones accessing the DB stats).

**Comment by ankitr** [comment]
Is there any authentication that's builtin to RethinkDB's dashboard or is that on us?

**Comment by gmittal** [comment]
Yup, they do have [built in authentication](https://rethinkdb.com/docs/security/).

**Comment by gmittal** [comment]
Migrated to Firebase. No more need for this.
